[package]
name = "naive_bayes_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jieba-rs = { version = "0.6", features = ["tfidf"] }
rand = "0.8"